config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'stories#index'

  devise_scope :user do
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
    get 'register', to: "devise/registrations#new", as: :register
  end

  resources :users, only: [:show]
  put "stories/:id/vote/:vote_value", to: "stories#vote", as: :story_vote
  put "stories/:story_id/submissions/:id/vote/:vote_value", to: "submissions#vote", as: :story_submission_vote

    resources :stories do
      resources :submissions, only: [:new, :create, :edit, :update, :destroy]
    end

  namespace :admin do
    resources :users, only: [:update, :destroy]
  end

authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories
  has_many :additions
  has_many :submissions
  has_many :views, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :username,
    uniqueness: { case_sensitive: false },
    presence: true
    validates :email,
    uniqueness: { case_sensitive: false },
    presence: true
  validates :encrypted_password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]

  attr_accessor :login

  def admin?
    role == 'admin'
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def voted_on?(voteable, voteable_type="Story")
    vote = Vote.find_by(user_id: id, voteable_id: voteable.id, voteable_type: voteable_type)
    vote ? vote.value : false
    #FIX RETURN TYPE.  HOW DO WE WANT TO MANAGE THIS
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    def destroy
      user = User.find(params[:id])
      user.destroy
      flash[:notice] = "User has been deleted"
      redirect_to root_path
    end

    def update
      user = User.find(params[:id])

      if user.update(user_params)
        flash[:notice] = "User has been set as Admin"
        redirect_to root_path
      end
    end

    private

    def user_params
      params.require(:user).permit(:role)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<h4><%= @user.username %></h4>
<p>Email: <%= @user.email %></p>
<p>Bio: <%= @user.description %></p>
<p><%= user_avatar(@user) %></p>
<% if @user.admin? %>
  <h5>ADMIN</h5>
<% end %>

<% if @user == current_user %>
  <%= link_to 'Edit Profile', edit_user_registration_path %><br>
<% end %>

<% if current_user && current_user.admin? || @user == current_user%>
  <%= link_to 'Delete User', admin_user_path(@user),
    method: :delete,
    data: { confirm: "Are you sure?" } %>
<% end %>
<% if current_user && current_user.admin? && @user != current_user %>
  <%= simple_form_for @user, url: admin_user_path(@user) do |f| %>
    <%= f.input :role, :as => :hidden, input_html: { value: "admin" } %>
    <%= f.button :submit, "Make user admin" %>
    <% end %>
<% end %>