config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'stories#index'

  devise_scope :user do
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
    get 'register', to: "devise/registrations#new", as: :register
  end

  resources :users, only: [:show]
  put "stories/:id/vote/:vote_value", to: "stories#vote", as: :story_vote
  put "stories/:story_id/submissions/:id/vote/:vote_value", to: "submissions#vote", as: :story_submission_vote

    resources :stories do
      resources :submissions, only: [:new, :create, :edit, :update, :destroy]
    end

  namespace :admin do
    resources :users, only: [:update, :destroy]
  end

authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  has_many :submissions, dependent: :destroy
  has_many :additions, dependent: :destroy
  has_many :votes, as: :voteable

  validates :title, presence: true
  validates :first_entry, presence: true
  validates :user, presence: true

  def self.search(search)
    where('title ILIKE ?', "%#{search}%")
  end

  def self.hot
    order(created_at: :desc)
  end

  def self.top
    Story.order(score: :desc, votes_count: :desc)
  end

  def self.controversial
    Story.order(votes_count: :desc, score: :desc)
  end

  def self.populate_index_with(query)
    if query[:search]
      Story.search(query[:search]).order(created_at: :desc)
    elsif query[:newest]
      Story.order(created_at: :desc)
    elsif query[:top]
      Story.top
    elsif query[:controversial]
      Story.controversial
    else
      Story.hot
    end
  end

  def best_submission
    submissions.joins(:votes).group('submissions.id').order('SUM(votes.value)').last
  end

  def promote_best_submission!
    best = best_submission
    Addition.create(user_id: best.user_id, story_id: best.story_id, body: best.body, score: best.vote_score)
    submissions.destroy_all
  end

  def submissions_to_be_viewed(user_id)
    submissions.find_by_sql("select submissions.*, users.username,
              count(views.submission_id) as views_count,
              (select count(*) from views
                where views.user_id=#{user_id} and views.submission_id=submissions.id group by id) as counted,
              (select sum(value) as score from votes
                where voteable_type='Submission' and voteable_id=submissions.id) as score
              from submissions
              left outer join views on views.submission_id=submissions.id
              join users on submissions.user_id=users.id
              where submissions.story_id = #{id}
              group by submissions.id, users.username
              order by counted desc, views_count")
    # shown_submissions = submissions.find_by_sql("select submissions.*, count(views.submission_id) as views_count from submissions
    #                         left outer join views on views.submission_id=submissions.id
    #                         where submissions.story_id = #{id}
    #                         group by submissions.id
    #                         order by count(views.user_id=#{user_id}), views_count")

    # Needs refactor to avoid SQL injections
  end

  def timestamp
    created_at.strftime('%B %d %Y %H:%M:%S')
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.populate_index_with(params).
      includes(:user, :additions).page(params[:page])
      # still an n+1 query here
  end

  def new
    authorize_user!
    @story = Story.new
  end

  def create
    authorize_user!
    @story = Story.new(story_params)
    @story.user = current_user
    if @story.save
      flash[:notice] = "Your story was submitted."
      StoriesWorker.perform_in(5.hours, @story.id)
      redirect_to story_path(@story)
    else
      flash[:notice] = "Invalid entry"
      render :new
    end
  end

  def show
    @story = Story.find(params[:id])
    @submission = Submission.new
    @additions = @story.additions.order(created_at: :desc)

    if current_user
      @submissions = @story.submissions_to_be_viewed(current_user.id)
      SubmissionsWorker.perform_async(submissions_to_id(@submissions), current_user.id)
    else
      @submissions = @story.submissions.
        find_by_sql("SELECT submissions.*, users.username,
                    (select sum(value) as score from votes
                      where voteable_type='Submission' and voteable_id=submissions.id) as score
                    from submissions
                    join users on users.id=submissions.user_id
                    where submissions.story_id = #{@story.id}
                    group by submissions.id, users.username")
    end
  end

  def edit
    @story = Story.find(params[:id])
    authorize_user_for_action!(@story.user)
  end

  def update
    @story = Story.find(params[:id])
    authorize_user_for_action!(@story.user)
    if @story.update(story_params)
      flash[:notice] = "Your story was edited."
      redirect_to story_path(@story)
    else
      flash[:notice] = "Invalid entry"
      render :new
    end
  end

  def destroy
    @story = Story.find(params[:id])
    authorize_user_for_action!(@story.user)

    Story.destroy(params[:id])
    redirect_to stories_path, notice: "Story deleted."
  end

  def vote
    story = Story.find(params[:id])
    if current_user
      vote = story.votes.find_or_initialize_by(user: current_user)
      vote.change_vote!(params[:vote_value].to_i)
      redirect_to stories_path
    else
      redirect_to new_user_session_path
    end
  end

  private

  def submissions_to_id(submissions)
    ids = []
    submissions.each { |s| ids << s.id}
    ids
  end

  def story_params
    params.require(:story).permit(:title, :first_entry, :search)
  end
end

app/views/stories/_form.html.erb
<%= simple_form_for @story do |f| %>
  <%= f.input :title, required: true %>

  <%= f.input :first_entry, required: true, as: :text %>

  <%= f.button :submit %>
<% end %>

app/views/stories/_story.html.erb
<div class="panel  row">
  <div class="large-1 columns">
    <%= render template: "votes/show", locals: { story: story} %>
  </div>
  <div class= "large-11 columns body_div">
    <p class="body_text"> <%=  image_tag("check.bmp", class: "story_image", size: "20", tag: "andrew") %> <strong><%= link_to story.title, story_path(story), class: "body_link" %></strong></p>
    <p class="body_description"> <%=render_markdown(story.first_entry)%></p>
    <p class="body_lower_data"><%=story.user ? (link_to story.user.username, user_path(story.user)) : "[DELETED]"%> |
      <%= story.timestamp %> | <a class="body_lower_data" href="#">comments</a></p>
      <div class="submission_text">
        <% story.additions.each do |addition| %>
          <p><%=  addition.body %></p>
        <% end %>
      </div>
  </div>
</div>
<br>

app/views/stories/_submissionvotes.html.erb
<div class="submission-votes">
  <div class="vote-container">
    <% if current_user && current_user.voted_on?(locals[:submission], "Submission") == 1 %>
      <%= link_to "UP", story_submission_vote_path(locals[:submission].story_id, locals[:submission], 1), method: :put, class: "submission-upvote"%>
    <% else %>
      <%= link_to "up", story_submission_vote_path(locals[:submission].story_id, locals[:submission], 1), method: :put, class: "submission-upvote" %>
    <% end %>
    <div class="vote-count"><%= locals[:submission].score ? locals[:submission].score : 0%></div>
    <% if current_user && current_user.voted_on?(locals[:submission], "Submission") == -1 %>
      <span class="vote-down">
        <%= link_to "DOWN", story_submission_vote_path(locals[:submission].story_id, locals[:submission], -1), method: :put, class: "submission-downvote" %>
      </span>
    <% else %>
      <span class="vote-down">
        <%= link_to "down", story_submission_vote_path(locals[:submission].story_id, locals[:submission], -1), method: :put, class: "submission-downvote" %>
      </span>
    <% end %>
  </div>
</div>

app/views/stories/edit.html.erb
<% provide(:title, 'Edit Story') %>
<div class="form-wrapper">
  <%= render "stories/form", story: @story %>
</div>

app/views/stories/index.html.erb
<% provide(:title, 'StoryBoardy: Make a story, We\'ll tell it') %>
<%= javascript_include_tag "scroll/endless_scroll" %>
<div class="row">
  <div class="show-for-small-only text-center">
    <%= button_to "New Story", new_story_path, method: :get, class: "fancy radius button mybutton" %>
  </div>
</div>
<div class="stories">
  <%= render @stories %>
</div>

app/views/stories/index.js.erb
$('#content').append("<%=j render(partial: 'story', collection: @stories, format: 'html') %>");

<% if @stories.current_page == @stories.total_pages %>
  $('#view-more').remove();
<% else %>
  $('#view-more a').attr('href', '<%= url_for(page: @stories.current_page + 1) %>');
<% end %>

app/views/stories/new.html.erb
<% provide(:title, 'Add New Story') %>
<div class="form-wrapper">
  <%= render "stories/form", story: @story %>
</div>

app/views/stories/show.html.erb
<% provide(:title, @story.title) %>
<div class="row">
  <div class="large-12 columns panel">
    <div class="row">
      <div class="large-1 columns">
        <%= render template: "votes/show", locals: { story: @story} %>
      </div>
      <div class="large-11 columns">
        <h4><%= @story.title %></h4>
        <p><%= render_markdown(@story.first_entry) %></p>
        <% @story.additions.each do |addition| %>
          <p><%=  addition.body %></p>
        <% end %>
      </div>
    </div>

  </div></div>
  <h3>Vote for the next entry:</h3>
  <% @submissions.each do |submission| %>
  <div class="row">
    <div class="large-1 columns">
      <%= render "submissionvotes", locals: { submission: submission } %>
    </div>
    <div class="large-11 columns">
      <%= render_markdown(submission.body) %>
      <p class="body_lower_data"> by <%=submission.username!="DELETED" ? (link_to submission.username, user_path(submission.user_id)) : "[DELETED]"%>
        <% if current_user && (current_user.admin? || current_user.id == submission.user_id) %>
        |
        <%= link_to 'Delete', story_submission_path(@story, submission), method: :delete, data: { confirm: 'Are you sure?'} %><br>
        <% end %></p>
      </div>
    </div>
    <br>
    <% end %>
    <% if current_user %>
    <%= simple_form_for([@story, @submission]) do |f| %>

    <%= f.input :body, required: true, as: :text, label: "Add your submission below:", input_html: { rows: 10 } %>

    <%= f.button :submit, "Submit" %>
    <% end %>
    <% if current_user.admin? || current_user.id == @story.user_id %>
    <%= button_to 'Delete Story', @story, method: :delete, data: { confirm: 'Are you sure?'}, class: "button tiny alert radius"%><br>
    <% end %>
    <% else %>
    <%= link_to "Log in to add to this story!", login_path %>
    <% end %>