config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'stories#index'

  devise_scope :user do
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
    get 'register', to: "devise/registrations#new", as: :register
  end

  resources :users, only: [:show]
  put "stories/:id/vote/:vote_value", to: "stories#vote", as: :story_vote
  put "stories/:story_id/submissions/:id/vote/:vote_value", to: "submissions#vote", as: :story_submission_vote

    resources :stories do
      resources :submissions, only: [:new, :create, :edit, :update, :destroy]
    end

  namespace :admin do
    resources :users, only: [:update, :destroy]
  end

authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable,
    polymorphic: true, counter_cache: true

  validates :user, presence: true
  validates :voteable_id, uniqueness: { scope: [:user_id, :voteable_type] }
  validates :voteable, presence: true
  validates :value, inclusion: { in: [1, -1] }
  validates :voteable_type, inclusion: { in: %w(Story Submission) }

  def upvote?
    value == 1
  end

  def downvote?
    value == -1
  end

  def change_vote!(user_vote)
    if user_vote == value
      voteable.increment!(:score, by = -user_vote) if voteable_type == "Story"
      delete
    else
      if value.nil?
        voteable.increment!(:score, by = user_vote) if voteable_type == "Story"
      else
        voteable.increment!(:score, by = user_vote * 2) if voteable_type == "Story"
      end
      self.value = user_vote
      save
    end
  end
end

app/views/votes/show.html.erb
<div class="story-votes">
  <div class="vote-container">
    <% if current_user && current_user.voted_on?(story) == 1 %>
      <%= link_to "UP", story_vote_path(story, 1), method: :put %>
    <% else %>
      <%= link_to "up", story_vote_path(story, 1), method: :put %>
    <% end %>
    <div class="vote-count"><%= story.vote_score %></div>
    <% if current_user && current_user.voted_on?(story) == -1 %>
      <span class="vote-down">
        <%= link_to "DOWN", story_vote_path(story, -1), method: :put %>
      </span>
    <% else %>
      <span class="vote-down">
        <%= link_to "down", story_vote_path(story, -1), method: :put %>
      </span>
    <% end %>
  </div>
</div>