config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'stories#index'

  devise_scope :user do
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
    get 'register', to: "devise/registrations#new", as: :register
  end

  resources :users, only: [:show]
  put "stories/:id/vote/:vote_value", to: "stories#vote", as: :story_vote
  put "stories/:story_id/submissions/:id/vote/:vote_value", to: "submissions#vote", as: :story_submission_vote

    resources :stories do
      resources :submissions, only: [:new, :create, :edit, :update, :destroy]
    end

  namespace :admin do
    resources :users, only: [:update, :destroy]
  end

authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>

<body>
  <div class="sticky">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">StoryBoardy</a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <li><%= link_to "Hot", root_path({ hot: true }) %></li>
          <li><%= link_to "New", root_path({ newest: true }) %></li>
          <li><%= link_to "Top", root_path({ top: true }) %></li>
          <li><%= link_to "Controversial", root_path({ controversial: true }) %></li>
          <li class="has-form">
            <%= form_tag stories_path, method: 'get', class: "has-form" do %>
              <div class="row collapse">
                <div class="large-8 small-9 columns">
                  <%= text_field_tag :search, nil, placeholder: "Search stories" %>
                </div>
                <div class="large-4 small-3 columns">
                  <%= submit_tag "Search", name: nil, class: "alert button expand" %>
                </div>
              </div>
            <% end %>
          </li>
        </ul>
        <ul class="right">
          <% if signed_in? %>
          <li class="show-for-large-up"><%= user_avatar(current_user) %></li>
          <li><%= link_to current_user.username, user_path(current_user) %></li>
          <li class="divider"></li>
          <li class="active show-for-large-up">
            <%= link_to 'Sign out', destroy_user_session_path, data: {method: 'delete'} %>
          </li>
          <% else %>
          <li class="active">
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
          <% end %>
        </ul>
      </section>
    </nav>
          <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
  </div>

  <div class="row" id="mainDiv">
    <div class="large-3 columns hide-for-small">
      <div class="panel">
      <% if current_user %>
        <p class="text-center"><%= link_to current_user.username, user_path(current_user) %></p>
        <div class="text-center"><%= button_to "New Story", new_story_path, method: :get, class: "fancy radius button" %></div>
      <% else %>
      <% end %>
      </div>
    </div>
    <div class="large-6 columns">
      <%= yield %>
    </div>
    <aside class="large-3 columns hide-for-small">
      <p><img src="http://placehold.it/300x440&text=[ad]"/></p>
      <p><img src="http://placehold.it/300x440&text=[ad]"/></p>
    </aside>
  </div>
  <%= javascript_include_tag "application" %>
</body>
</html>